USE [master]
GO

/****** Object:  Database [sessionapidb]    Script Date: 17.3.2022. 4:08:45 ******/
CREATE DATABASE [sessionapidb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sessionapidb', FILENAME = N'C:\Users\yuri\sessionapidb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sessionapidb_log', FILENAME = N'C:\Users\yuri\sessionapidb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sessionapidb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sessionapidb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sessionapidb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sessionapidb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sessionapidb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sessionapidb] SET ARITHABORT OFF 
GO

ALTER DATABASE [sessionapidb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [sessionapidb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sessionapidb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sessionapidb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sessionapidb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sessionapidb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sessionapidb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sessionapidb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sessionapidb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sessionapidb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [sessionapidb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sessionapidb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sessionapidb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sessionapidb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sessionapidb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sessionapidb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [sessionapidb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sessionapidb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sessionapidb] SET  MULTI_USER 
GO

ALTER DATABASE [sessionapidb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sessionapidb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sessionapidb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sessionapidb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sessionapidb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sessionapidb] SET QUERY_STORE = OFF
GO

USE [sessionapidb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [sessionapidb] SET  READ_WRITE 
GO

